# Generated by Django 4.0.3 on 2022-03-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Likes', 'verbose_name_plural': 'Likes'},
        ),
    ]
